# Generated by Django 6.0.4 on 2026-04-22 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=50)),
                ('full_name', models.CharField(max_length=200)),
                ('age', models.PositiveIntegerField()),
                ('skill', models.CharField(max_length=50)),
                ('score', models.PositiveIntegerField()),
                ('level', models.CharField(choices=[('Seeds', 'Seeds'), ('Sparks', 'Sparks'), ('Rays', 'Rays'), ('Crystals', 'Crystals')], max_length=20)),
                ('status', models.CharField(choices=[('Excellent', 'Excellent'), ('Good', 'Good'), ('Needs Support', 'Needs Support')], max_length=30)),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
