# Generated by Django 6.0.4 on 2026-04-22 20:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentresult',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='studentresult',
            name='score',
        ),
        migrations.RemoveField(
            model_name='studentresult',
            name='skill',
        ),
        migrations.RemoveField(
            model_name='studentresult',
            name='status',
        ),
        migrations.AddField(
            model_name='studentresult',
            name='listening_answers',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentresult',
            name='listening_score',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='studentresult',
            name='reading_score',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='studentresult',
            name='speaking_score',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='studentresult',
            name='total_score',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='studentresult',
            name='writing_answer',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentresult',
            name='writing_score',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='studentresult',
            name='level',
            field=models.CharField(choices=[('Seeds', 'Seeds'), ('Sparks', 'Sparks'), ('Rays', 'Rays'), ('Crystals', 'Crystals')], default='Seeds', max_length=20),
        ),
        migrations.AlterField(
            model_name='studentresult',
            name='student_id',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
