# Generated by Django 6.0.4 on 2026-04-23 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0002_remove_studentresult_comment_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentresult',
            old_name='level',
            new_name='listening_level',
        ),
        migrations.RemoveField(
            model_name='studentresult',
            name='writing_answer',
        ),
        migrations.AddField(
            model_name='studentresult',
            name='listening_reached_level',
            field=models.CharField(choices=[('Seeds', 'Seeds'), ('Sparks', 'Sparks'), ('Rays', 'Rays'), ('Crystals', 'Crystals')], default='Seeds', max_length=20),
        ),
        migrations.AddField(
            model_name='studentresult',
            name='overall_level',
            field=models.CharField(choices=[('Seeds', 'Seeds'), ('Sparks', 'Sparks'), ('Rays', 'Rays'), ('Crystals', 'Crystals')], default='Seeds', max_length=20),
        ),
        migrations.AddField(
            model_name='studentresult',
            name='reading_level',
            field=models.CharField(choices=[('Seeds', 'Seeds'), ('Sparks', 'Sparks'), ('Rays', 'Rays'), ('Crystals', 'Crystals')], default='Seeds', max_length=20),
        ),
        migrations.AddField(
            model_name='studentresult',
            name='speaking_level',
            field=models.CharField(choices=[('Seeds', 'Seeds'), ('Sparks', 'Sparks'), ('Rays', 'Rays'), ('Crystals', 'Crystals')], default='Seeds', max_length=20),
        ),
        migrations.AddField(
            model_name='studentresult',
            name='writing_answers',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='studentresult',
            name='writing_level',
            field=models.CharField(choices=[('Seeds', 'Seeds'), ('Sparks', 'Sparks'), ('Rays', 'Rays'), ('Crystals', 'Crystals')], default='Seeds', max_length=20),
        ),
        migrations.AddField(
            model_name='studentresult',
            name='writing_reached_level',
            field=models.CharField(choices=[('Seeds', 'Seeds'), ('Sparks', 'Sparks'), ('Rays', 'Rays'), ('Crystals', 'Crystals')], default='Seeds', max_length=20),
        ),
        migrations.AlterField(
            model_name='studentresult',
            name='listening_answers',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='studentresult',
            name='listening_score',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='studentresult',
            name='reading_score',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='studentresult',
            name='speaking_score',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='studentresult',
            name='writing_score',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
