# Generated by Django 6.0.4 on 2026-04-26 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0003_rename_level_studentresult_listening_level_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentresult',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='studentresult',
            name='overall_level',
        ),
        migrations.RemoveField(
            model_name='studentresult',
            name='total_score',
        ),
        migrations.AddField(
            model_name='studentresult',
            name='listening_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentresult',
            name='writing_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='studentresult',
            name='full_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='studentresult',
            name='listening_level',
            field=models.CharField(default='Seeds', max_length=50),
        ),
        migrations.AlterField(
            model_name='studentresult',
            name='listening_reached_level',
            field=models.CharField(default='Not started', max_length=50),
        ),
        migrations.AlterField(
            model_name='studentresult',
            name='reading_level',
            field=models.CharField(default='Seeds', max_length=50),
        ),
        migrations.AlterField(
            model_name='studentresult',
            name='speaking_level',
            field=models.CharField(default='Seeds', max_length=50),
        ),
        migrations.AlterField(
            model_name='studentresult',
            name='writing_level',
            field=models.CharField(default='Seeds', max_length=50),
        ),
        migrations.AlterField(
            model_name='studentresult',
            name='writing_reached_level',
            field=models.CharField(default='Not started', max_length=50),
        ),
    ]
